"""modifying database structure

Revision ID: 1a708e202b47
Revises: 
Create Date: 2023-10-09 19:59:11.730975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a708e202b47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steamid_data',
    sa.Column('steamid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('buildid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('steamid')
    )
    op.create_table('discord_server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serverid', sa.String(), nullable=False),
    sa.Column('steamid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['steamid'], ['steamid_data.steamid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_server')
    op.drop_table('steamid_data')
    # ### end Alembic commands ###
