"""moving to asyncpg

Revision ID: 389e292bb0d2
Revises: 
Create Date: 2023-10-12 05:03:14.939667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389e292bb0d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serverid', sa.String(), nullable=False),
    sa.Column('channelid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channelid'),
    sa.UniqueConstraint('serverid')
    )
    op.create_table('steamid_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steamid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('buildid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steamid')
    )
    op.create_table('tracking',
    sa.Column('steamid', sa.Integer(), nullable=True),
    sa.Column('serverid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['serverid'], ['discord_server.id'], ),
    sa.ForeignKeyConstraint(['steamid'], ['steamid_data.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking')
    op.drop_table('steamid_data')
    op.drop_table('discord_server')
    # ### end Alembic commands ###
